<div class="ctrlHolder<?= $this->last;?> <?php if($this->element->getMessages()) { ?>error<?php } ?>">
	<label for="<?= $this->element->getId(); ?>">
		<?php if($this->element->isRequired()) { ?><em>*</em><?php } ?>
		<?= $this->element->getLabel(); ?>
	</label>
	<textarea 
		name="<?= $this->element->getName(); ?>" 
		id="<?= $this->element->getId(); ?>" 
		class="tinymce <?= $this->element->class; ?>"
		style="<?= $this->element->style; ?>"><?= $this->element->getValue(); ?></textarea>
	<?php if ($this->element->getMessages()){ echo $this->element->getView()->formErrors($this->element->getMessages()); }; ?>
	<?php if ($this->element->getDescription()){ ?><p class="formHint"><span><?= $this->element->getDescription(); ?></span></p><?php } ?>
</div>

<?php $this->placeholder('UniForm')->captureStart(); ?>
$('#<?= $this->element->getId(); ?>').tinymce({
    script_url : '/js/tinymce/jscripts/tiny_mce/tiny_mce.js',
    skin : "o2k7",
    skin_variant : "silver",
    theme : "advanced",
    plugins : "safari,advlink,paste,preview,advimage,advlink,fullscreen,inlinepopups",
    entity_encoding : "raw",
    
    theme_advanced_resizing : true,
    theme_advanced_buttons1 : "bold,italic,removeformat,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,link,unlink,|,cleanup,pasteword,|,code,preview,fullscreen,|,image,file",
    theme_advanced_buttons2 : "formatselect,styleselect",
    theme_advanced_buttons3 : "",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_statusbar_location : "bottom",

	<?php if($this->element->fileList) { ?>
	external_image_list_url : "<?= $this->element->fileList; ?>",
	external_link_list_url : "<?= $this->element->fileList; ?>",
	<?php } ?>
    relative_urls : false,
	theme_advanced_blockformats : "p,div,pre,h2,h3,h4,h5,h6",
	content_css : '',
	body_id: 'content',
	dialog_type : 'modal',
	valid_elements : "*[*]",
	extended_valid_elements : "*[*]"
});
<?php $this->placeholder('UniForm')->captureEnd(); ?>
